{{/*
Override values for the Grafana subchart
This file configures Grafana to use our custom datasources and dashboard providers
*/}}
{{- if .Values.grafana.enabled }}
---
# Grafana Deployment (standalone, not using subchart for more control)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aiobs.grafana.fullname" . }}
  labels:
    {{- include "aiobs.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "aiobs.name" . }}-grafana
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "aiobs.name" . }}-grafana
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/datasources: {{ include (print $.Template.BasePath "/configmap-grafana.yaml") . | sha256sum }}
    spec:
      securityContext:
        fsGroup: 472
        runAsUser: 472
        runAsGroup: 472
      initContainers:
        # Init container to set up directory permissions
        - name: init-chown-data
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          command:
            - sh
            - -c
            - |
              mkdir -p /var/lib/grafana/plugins
              mkdir -p /var/lib/grafana/dashboards/aiobs
              chown -R 472:472 /var/lib/grafana
              chmod -R 755 /var/lib/grafana
              echo "Grafana data directory initialized."
          volumeMounts:
            - name: storage
              mountPath: /var/lib/grafana
        {{- if .Values.dorisPlugin.enabled }}
        # Copy doris-app plugin and dashboards from image
        - name: copy-assets
          image: {{ .Values.dorisPlugin.image.repository }}:{{ .Values.dorisPlugin.image.tag }}
          imagePullPolicy: {{ .Values.dorisPlugin.image.pullPolicy | default "IfNotPresent" }}
          securityContext:
            runAsUser: 0
          command:
            - sh
            - -c
            - |
              echo "Copying doris-app plugin..."
              cp -r /assets/plugins/* /var/lib/grafana/plugins/
              echo "Copying dashboards..."
              cp -r /assets/dashboards/* /var/lib/grafana/dashboards/aiobs/
              chown -R 472:472 /var/lib/grafana/plugins /var/lib/grafana/dashboards
              chmod -R 755 /var/lib/grafana/plugins /var/lib/grafana/dashboards
              echo "Assets installed successfully."
              ls -la /var/lib/grafana/plugins/
              ls -la /var/lib/grafana/dashboards/aiobs/
          volumeMounts:
            - name: storage
              mountPath: /var/lib/grafana
        {{- end }}
        {{- if eq .Values.doris.mode "internal" }}
        # Wait for Doris to be ready before starting
        - name: wait-for-doris
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for Doris FE to be ready..."
              until nc -z {{ include "aiobs.doris.clusterName" . }}-fe-service 9030; do
                echo "Doris FE not ready, waiting..."
                sleep 5
              done
              echo "Doris FE is ready! Starting Grafana..."
        {{- end }}
      containers:
        - name: grafana
          image: "grafana/grafana:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.grafana.adminUser | quote }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafana.adminPassword | quote }}
            - name: GF_INSTALL_PLUGINS
              value: {{ .Values.grafana.plugins | join "," | quote }}
            - name: GF_LOG_LEVEL
              value: "info"
            - name: GF_PATHS_DATA
              value: /var/lib/grafana
            - name: GF_PATHS_PLUGINS
              value: /var/lib/grafana/plugins
            {{- if .Values.dorisPlugin.enabled }}
            # Allow loading unsigned doris-app plugin
            - name: GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS
              value: "doris-app"
            {{- end }}
            # Enable feature toggles for tracing
            - name: GF_FEATURE_TOGGLES_ENABLE
              value: "traceQLStreaming metricsSummary"
            {{- range $key, $value := .Values.grafana.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 120
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
          resources:
            {{- toYaml .Values.grafana.resources | nindent 12 }}
          volumeMounts:
            - name: storage
              mountPath: /var/lib/grafana
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
            - name: dashboard-providers
              mountPath: /etc/grafana/provisioning/dashboards
              readOnly: true
      volumes:
        - name: storage
          {{- if .Values.grafana.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "aiobs.grafana.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: datasources
          configMap:
            name: {{ include "aiobs.grafana.fullname" . }}-datasources
        - name: dashboard-providers
          configMap:
            name: {{ include "aiobs.grafana.fullname" . }}-dashboard-providers

---
# Grafana Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aiobs.grafana.fullname" . }}
  labels:
    {{- include "aiobs.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - name: http
      port: {{ .Values.grafana.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "aiobs.name" . }}-grafana
    app.kubernetes.io/instance: {{ .Release.Name }}

{{- if .Values.grafana.persistence.enabled }}
---
# Grafana PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aiobs.grafana.fullname" . }}
  labels:
    {{- include "aiobs.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.grafana.persistence.storageClassName }}
  storageClassName: {{ .Values.grafana.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
{{- end }}
{{- end }}
